name: musicly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  audio_service: ^0.18.17
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  envied: ^1.1.1
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_gen_runner: ^5.10.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.46
  logger: ^2.5.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pkg_dio:
    path: pkg_dio
  rxdart: ^0.28.0
  skeletonizer: ^1.4.3

dev_dependencies:
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  hive_ce_generator: ^1.8.2
  json_serializable: ^6.9.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts: [
    {
      family: "Urbanist",
      fonts: [
        {asset: "assets/fonts/Urbanist-Light.ttf",weight: 300},
        {asset: "assets/fonts/Urbanist-Regular.ttf",weight: 400},
        {asset: "assets/fonts/Urbanist-Medium.ttf",weight: 500},
        {asset: "assets/fonts/Urbanist-SemiBold.ttf",weight: 600},
        {asset: "assets/fonts/Urbanist-Bold.ttf",weight: 700},
      ]
    }
  ]
  assets:
      [
        "assets/icons/",
        "assets/json/"
      ]

flutter_gen:
  {
    line_length: 120,
    integrations: { flutter_svg: true, lottie: true },
    fonts: { enabled: true, outputs: { class_name: FontFamily }, },
  }
