name: pkg_dio
description: Dio helper package
version: 0.0.1

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  logger: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  very_good_analysis: ^7.0.0
